service: api

custom:

  webpack: ../../tools/build/stack/webpack.config.js

  ssm:
    api/api/endpoint: 'blub'


provider:
  name: aws
  runtime: nodejs6.10
  stage: int
  region: eu-central-1
  memorySize: 256
  timeout: 60 # optional, in seconds, default is 6
  environment:
    STAGE : ${opt:stage, self:provider.stage}
    REGION: ${opt:region, self:provider.region}

  iamRoleStatements:

plugins:
  - "@eventstorejs/serverless-eventstore"
  - serverless-annotations
  - serverless-deploy-ssm
  - serverless-webpack
  - serverless-log-aggregate
  - serverless-stack-manager

functions:


resources:
  Resources:

