service: api

custom:

  webpack: ../config/stack/webpack.config.js

  ssm:
    api/api/endpoint:
      Fn::Join :
        - ""
        - - https://
          - Ref : ApiGatewayRestApi
          - .execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}


provider:
  name: aws
  runtime: nodejs6.10
  stage: int
  region: eu-central-1
  memorySize: 256
  timeout: 60 # optional, in seconds, default is 6
  environment:
    STAGE : ${opt:stage, self:provider.stage}
    REGION: ${opt:region, self:provider.region}

  iamRoleStatements:

plugins:
  - "@eventstorejs/serverless-eventstore"
  - serverless-annotations
  - serverless-deploy-ssm
  - serverless-webpack
  - serverless-log-aggregate
  - serverless-stack-manager

functions:


resources:
  Resources:

